services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: devuser
      POSTGRES_DB: devdb
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  db-store:
